#!/bin/bash
g++ -std=c++20 -O3 -c vec.cpp -o vec.o 
g++ -std=c++20 -O3 -c matrix.cpp -o matrix.o
g++ -std=c++20 -O3 -c 3d.cpp -o 3d.o
g++ -std=c++20 -O3 -c mbox.cpp -o mbox.o

ar -rcs libmbox.a vec.o matrix.o 3d.o mbox.o